# Stage 1: Build the Angular application
FROM node:20-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --prod

# Stage 2: Serve the built application using Nginx
FROM nginx:alpine

# Copy the built Angular files to Nginx public folder
COPY --from=builder /app/dist/* /usr/share/nginx/html

# Expose Nginx port
EXPOSE 80
